spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true
    username: 
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa
    database-platform : org.hibernate.dialect.MySQL5Dialect
    generate-ddl : true
    hibernate.ddl-auto : update
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

